# Generated by Django 5.1 on 2024-10-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_magazines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazines',
            new_name='Magazine',
        ),
    ]
