# Generated by Django 5.1 on 2024-10-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_magazines_magazine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='content',
            field=models.BinaryField(),
        ),
    ]
