# Generated by Django 5.1 on 2025-01-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourism',
            name='location',
        ),
        migrations.AddField(
            model_name='tourism',
            name='title',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourism',
            name='content',
            field=models.BinaryField(),
        ),
    ]
